#!/usr/bin/perl
################################################
#      Copyright 2004-2025 RDN Networks        #
#      Logout Module                           #
################################################

use CGI;
use CGI::Cookie;
$rdn = new CGI;

require "/var/www/cgi-bin/rdn_server/config.conf";
require "/var/www/cgi-bin/rdn_server/rdn_session";

# Expire the session cookie
&rdn_expiresession();

# Redirect to login page
print "Location: $rdn_server$rdn_port/$rdn_bin/login.html\n\n";
exit;
